Add "only" option
robertogallea/pulse-db-size pull request #4
Opened 2024-12-13 15:34 UTC by jannismilz

Hey @robertogallea, just came across this package and wanted to implement it. (Great idea, I love it!)

I really wanted the option "only" instead of "ignore" so I implemented it.

Would love a review and if I forgot anything 🙌
Feel free to ask any questions.

2024-12-13 17:43 UTC, robertogallea commented
Hi @jannismilz !
I think it is quite a useful addition, thank you! ~~I'll merge it right now and create a new version as soon as possible.~~

Thanks again!

Please address the comments ;)

2024-12-13 17:46 UTC, robertogallea requested changes

2024-12-13 17:46 UTC, robertogallea commented on README.md
> +            ]
I am from mobile but it looks like there is a missing comma.

2024-12-13 17:49 UTC, robertogallea requested changes

2024-12-13 17:49 UTC, robertogallea commented on src/Recorders/DBSizeRecorder.php
> +                $operator = 'IN'
Missing semicolon

2024-12-13 17:49 UTC, robertogallea commented on src/Recorders/DBSizeRecorder.php
> +                $operator = 'NOT IN'
Missing semicolon

2024-12-13 19:04 UTC, jannismilz reviewed
Thanks for the rapid response! 

Sorry my bad, I fixed the typos.

2024-12-13 20:08 UTC, robertogallea commented
Unfortunately tests do not pass yet.

2024-12-13 20:10 UTC, jannismilz commented
> Unfortunately tests do not pass yet. 

Gonna fix that tomorrow. Was expected..

2024-12-13 21:24 UTC, jannismilz commented
@robertogallea I think I found the problem. Should be fixed now.

2024-12-15 15:35 UTC, jannismilz commented
@robertogallea any update?

2024-12-17 09:59 UTC, robertogallea approved these changes

2024-12-17 09:59 UTC, merged

2024-12-17 09:59 UTC, robertogallea commented
Well done! Thanks!

2024-12-17 10:22 UTC, robertogallea commented
> @robertogallea any update?

Merged and v1.1.0 published